site_name: My Blog
site_url: https://wgz-w.github.io/
theme:
  name: material
  
  palette:
    - primary: cyan
  
  features:
    - navigation.tabs
    - navigation.path
  
  favicon: img/favicon.ico

plugins:
  - search
  - blog
