site_name: My Blog
site_url: https://wgz-w.github.io/
theme:
  name: material
  
  palette:
    - primary: cyan
  
  features:
    - navigation.tabs
    - navigation.path
  
  favicon: img/favicon.ico

plugins:
  - search
  - blog

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  
  - Blogs:
    - Blogs/index.md
    - Blogs/daily.md
    - Blogs/goods.md
    - Blogs/how-to-read-paper.md
    - Blogs/how-to-sleep.md
    - Blogs/life-study.md
    - Blogs/minihabits.md
    - Blogs/sentences.md
    - Blogs/works.md
  
  - Study:
    - Study/index.md
    - Deep Learning:
      - Study/Deep-Learning/preliminary.md
      - Study/Deep-Learning/linear-network.md
      - Study/Deep-Learning/deep-learning.md
    - Machine Learnning:
      - Study/Machine-Learning/machine-learning.md
    - Algorithm:
      - Study/Algorithm/algorithm.md
    - Pytorch:
      - Study/Pytorch/pytorch.md
    - Python:
      - Study/Python/python.md
    - Study/courses.md
    - Study/english.md
    - Study/linux.md
    - Study/matrix.md
    - Study/programming-language.md
    - Study/study-guide.md
  
  - BookList:
    - BookList/novels.md
    - BookList/English-novels.md
    - BookList/Personal-growth.md
    - BookList/biography.md
    - BookList/computer.md
    - BookList/history.md
    - BookList/literature.md
  
  - BookMark:
    - BookMark/blogs.md
    - BookMark/bookmarks.md
    - BookMark/download-book.md
    - BookMark/manual-doc.md
  
  - Git:
    - Git/index.md
    - Git/connect-with-ssh.md
    - Git/git-basic.md
    - Git/github-actions.md
    - Git/troubleshooting-ssh.md
  
  - Linux:
    - Linux/index.md
    - Linux/basic.md
    - Linux/grub-theme.md
    - ArchLinux:
      - Linux/ArchLinux-Linux/installation.md
      - Linux/ArchLinux-Linux/applications.md
      - Linux/ArchLinux-Linux/configuration.md
      - Linux/ArchLinux-Linux/desktop.md
      - Linux/ArchLinux-Linux/mysecond.md
    - Tools:
      - Linux/Tools/dwm.md
      - Linux/Tools/lazygit.md
      - Linux/Tools/neovim.md
      - Linux/Tools/ranger.md
      - Linux/Tools/tldr.md
      - Linux/Tools/tumx.md
      - Linux/Tools/v2raya.md
      - Linux/Tools/vscode.md
  
  - Vim:
    - Vim/index.md
    - Vim/editor.md
    - Vim/nvim.md
    - Vim/vim-basic.md
